---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/items":
    get:
      summary: list items
      responses:
        '200':
          description: successful
    post:
      summary: create item
      responses:
        '200':
          description: successful
  "/api/v1/items/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit item
      responses:
        '200':
          description: successful
  "/api/v1/items/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show item
      responses:
        '200':
          description: successful
    patch:
      summary: update item
      responses:
        '200':
          description: successful
    put:
      summary: update item
      responses:
        '200':
          description: successful
    delete:
      summary: delete item
      responses:
        '200':
          description: successful
  "/api/v1/reserveds":
    get:
      summary: list reserveds
      responses:
        '200':
          description: successful
  "/api/v1/items/{item_id}/reserveds":
    parameters:
    - name: item_id
      in: path
      description: item_id
      required: true
      schema:
        type: string
    post:
      summary: create reserved
      responses:
        '200':
          description: successful
  "/api/v1/items/{item_id}/reserveds/{id}/edit":
    parameters:
    - name: item_id
      in: path
      description: item_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit reserved
      responses:
        '200':
          description: successful
  "/api/v1/items/{item_id}/reserveds/{id}":
    parameters:
    - name: item_id
      in: path
      description: item_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reserved
      responses:
        '200':
          description: successful
    patch:
      summary: update reserved
      responses:
        '200':
          description: successful
    put:
      summary: update reserved
      responses:
        '200':
          description: successful
    delete:
      summary: delete reserved
      responses:
        '200':
          description: successful
  "/signup/cancel":
    get:
      summary: cancel registration
      responses:
        '200':
          description: successful
  "/signup/sign_up":
    get:
      summary: new registration
      responses:
        '200':
          description: successful
  "/signup/edit":
    get:
      summary: edit registration
      responses:
        '200':
          description: successful
  "/signup":
    patch:
      summary: update registration
      responses:
        '200':
          description: successful
    put:
      summary: update registration
      responses:
        '200':
          description: successful
    delete:
      summary: delete registration
      responses:
        '200':
          description: successful
    post:
      summary: create registration
      responses:
        '200':
          description: successful
  "/login":
    get:
      summary: new session
      responses:
        '200':
          description: successful
    post:
      summary: create session
      responses:
        '200':
          description: successful
  "/logout":
    delete:
      summary: delete session
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
